services:
  redis:
    container_name: "redis-server"
    image: redis:7.2.5
    ports:
      - "6379:6379"
  subscriber:
    container_name: "subscribers"
    image: pmoraisf/redis-api:subscribers
    entrypoint: ["python3", "subscriber-async.py"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=
    depends_on:
      - redis
  main:
    container_name: "main"
    image: pmoraisf/redis-api:main
    entrypoint: ["python3", "server-async.py"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=
    depends_on:
      - redis
      - subscriber