FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean

WORKDIR /app

COPY subscribertest.py /app/

RUN apt install -y python3-redis

CMD ["python3", "subscribertest.py"]
